name: health_example
description: Demonstrates how to use the health plugin.
publish_to: "none"
version: 4.5.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^10.2.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  google_sign_in: ^6.1.6
  chart_sparkline: ^1.0.15+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  health:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/images/Steps.png
    - assets/images/HeartRate.png
    - assets/images/Calories.png
    - assets/images/Spo2.png
    - assets/images/logo.png
